FROM python:3
WORKDIR /usr/src/app
COPY requirements.local.txt ./
RUN pip install --default-timeout=1000 --no-cache-dir -r requirements.local.txt
RUN pip freeze --all > /tmp/pip_versions.txt
COPY . .
CMD [ "uvicorn", "main:app","--host","0.0.0.0","--port","8080" ]